export const COUNTRIES = [
  { code: "AF", name: "Afganistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algieria" },
  { code: "AD", name: "Andora" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AQ", name: "Antarktyda" },
  { code: "AG", name: "Antigua i Barbuda" },
  { code: "SA", name: "Arabia Saudyjska" },
  { code: "AR", name: "Argentyna" },
  { code: "AM", name: "Armenia" },
  { code: "AW", name: "Aruba" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbejdżan" },
  { code: "BS", name: "Bahamy" },
  { code: "BH", name: "Bahrajn" },
  { code: "BD", name: "Bangladesz" },
  { code: "BB", name: "Barbados" },
  { code: "BE", name: "Belgia" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BM", name: "Bermudy" },
  { code: "BT", name: "Bhutan" },
  { code: "BY", name: "Białoruś" },
  { code: "BO", name: "Boliwia" },
  { code: "BA", name: "Bośnia i Hercegowina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazylia" },
  { code: "BN", name: "Brunei" },
  { code: "IO", name: "Brytyjskie Terytorium Oceanu Indyjskiego" },
  { code: "VG", name: "Brytyjskie Wyspy Dziewicze" },
  { code: "BG", name: "Bułgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "Chiny" },
  { code: "HR", name: "Chorwacja" },
  { code: "CY", name: "Cypr" },
  { code: "TD", name: "Czad" },
  { code: "ME", name: "Czarnogóra" },
  { code: "CZ", name: "Czechy" },
  { code: "DK", name: "Dania" },
  { code: "CD", name: "Demokratyczna Republika Konga" },
  { code: "DM", name: "Dominika" },
  { code: "DO", name: "Dominikana" },
  { code: "DJ", name: "Dżibuti" },
  { code: "EG", name: "Egipt" },
  { code: "EC", name: "Ekwador" },
  { code: "ER", name: "Erytrea" },
  { code: "EE", name: "Estonia" },
  { code: "ET", name: "Etiopia" },
  { code: "FK", name: "Falklandy" },
  { code: "FJ", name: "Fidżi" },
  { code: "PH", name: "Filipiny" },
  { code: "FI", name: "Finlandia" },
  { code: "FR", name: "Francja" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GR", name: "Grecja" },
  { code: "GD", name: "Grenada" },
  { code: "GL", name: "Grenlandia" },
  { code: "GE", name: "Gruzja" },
  { code: "GU", name: "Guam" },
  { code: "GY", name: "Gujana" },
  { code: "GF", name: "Gujana Francuska" },
  { code: "GP", name: "Gwadelupa" },
  { code: "GT", name: "Gwatemala" },
  { code: "GN", name: "Gwinea" },
  { code: "GW", name: "Gwinea Bissau" },
  { code: "GQ", name: "Gwinea Równikowa" },
  { code: "HT", name: "Haiti" },
  { code: "ES", name: "Hiszpania" },
  { code: "NL", name: "Holandia" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hongkong" },
  { code: "IN", name: "Indie" },
  { code: "ID", name: "Indonezja" },
  { code: "IQ", name: "Irak" },
  { code: "IR", name: "Iran" },
  { code: "IE", name: "Irlandia" },
  { code: "IS", name: "Islandia" },
  { code: "IL", name: "Izrael" },
  { code: "JM", name: "Jamajka" },
  { code: "JP", name: "Japonia" },
  { code: "YE", name: "Jemen" },
  { code: "JO", name: "Jordania" },
  { code: "KY", name: "Kajmany" },
  { code: "KH", name: "Kambodża" },
  { code: "CM", name: "Kamerun" },
  { code: "CA", name: "Kanada" },
  { code: "QA", name: "Katar" },
  { code: "KZ", name: "Kazachstan" },
  { code: "KE", name: "Kenia" },
  { code: "KG", name: "Kirgistan" },
  { code: "KI", name: "Kiribati" },
  { code: "CO", name: "Kolumbia" },
  { code: "KM", name: "Komory" },
  { code: "CG", name: "Kongo" },
  { code: "KR", name: "Korea Południowa" },
  { code: "KP", name: "Korea Północna" },
  { code: "CR", name: "Kostaryka" },
  { code: "CU", name: "Kuba" },
  { code: "KW", name: "Kuwejt" },
  { code: "LA", name: "Laos" },
  { code: "LS", name: "Lesotho" },
  { code: "LB", name: "Liban" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libia" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Litwa" },
  { code: "LU", name: "Luksemburg" },
  { code: "LV", name: "Łotwa" },
  { code: "MK", name: "Macedonia Północna" },
  { code: "MG", name: "Madagaskar" },
  { code: "YT", name: "Majotta" },
  { code: "MO", name: "Makau" },
  { code: "MW", name: "Malawi" },
  { code: "MV", name: "Malediwy" },
  { code: "MY", name: "Malezja" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MP", name: "Mariany Północne" },
  { code: "MA", name: "Maroko" },
  { code: "MQ", name: "Martynika" },
  { code: "MR", name: "Mauretania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Meksyk" },
  { code: "FM", name: "Mikronezja" },
  { code: "MM", name: "Mjanma (Birma)" },
  { code: "MD", name: "Mołdawia" },
  { code: "MC", name: "Monako" },
  { code: "MN", name: "Mongolia" },
  { code: "MS", name: "Montserrat" },
  { code: "MZ", name: "Mozambik" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "DE", name: "Niemcy" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NI", name: "Nikaragua" },
  { code: "NU", name: "Niue" },
  { code: "NF", name: "Norfolk" },
  { code: "NO", name: "Norwegia" },
  { code: "NC", name: "Nowa Kaledonia" },
  { code: "NZ", name: "Nowa Zelandia" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestyna" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua-Nowa Gwinea" },
  { code: "PY", name: "Paragwaj" },
  { code: "PE", name: "Peru" },
  { code: "PN", name: "Pitcairn" },
  { code: "PF", name: "Polinezja Francuska" },
  { code: "PL", name: "Polska" },
  { code: "PR", name: "Portoryko" },
  { code: "PT", name: "Portugalia" },
  { code: "ZA", name: "Republika Południowej Afryki" },
  { code: "CF", name: "Republika Środkowoafrykańska" },
  { code: "CV", name: "Republika Zielonego Przylądka" },
  { code: "RE", name: "Reunion" },
  { code: "RU", name: "Rosja" },
  { code: "RO", name: "Rumunia" },
  { code: "RW", name: "Rwanda" },
  { code: "EH", name: "Sahara Zachodnia" },
  { code: "KN", name: "Saint Kitts i Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent i Grenadyny" },
  { code: "BL", name: "Saint-Barthélemy" },
  { code: "MF", name: "Saint-Martin" },
  { code: "PM", name: "Saint-Pierre i Miquelon" },
  { code: "SV", name: "Salwador" },
  { code: "WS", name: "Samoa" },
  { code: "AS", name: "Samoa Amerykańskie" },
  { code: "SM", name: "San Marino" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seszele" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapur" },
  { code: "SK", name: "Słowacja" },
  { code: "SI", name: "Słowenia" },
  { code: "SO", name: "Somalia" },
  { code: "LK", name: "Sri Lanka" },
  { code: "US", name: "Stany Zjednoczone" },
  { code: "SZ", name: "Suazi (Eswatini)" },
  { code: "SD", name: "Sudan" },
  { code: "SS", name: "Sudan Południowy" },
  { code: "SR", name: "Surinam" },
  { code: "SJ", name: "Svalbard i Jan Mayen" },
  { code: "SY", name: "Syria" },
  { code: "CH", name: "Szwajcaria" },
  { code: "SE", name: "Szwecja" },
  { code: "TJ", name: "Tadżykistan" },
  { code: "TH", name: "Tajlandia" },
  { code: "TW", name: "Tajwan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TL", name: "Timor Wschodni" },
  { code: "TG", name: "Togo" },
  { code: "TK", name: "Tokelau" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trynidad i Tobago" },
  { code: "TN", name: "Tunezja" },
  { code: "TR", name: "Turcja" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TC", name: "Turks i Caicos" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraina" },
  { code: "UY", name: "Urugwaj" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "WF", name: "Wallis i Futuna" },
  { code: "VA", name: "Watykan" },
  { code: "VE", name: "Wenezuela" },
  { code: "HU", name: "Węgry" },
  { code: "GB", name: "Wielka Brytania" },
  { code: "VN", name: "Wietnam" },
  { code: "IT", name: "Włochy" },
  { code: "CI", name: "Wybrzeże Kości Słoniowej" },
  { code: "CX", name: "Wyspa Bożego Narodzenia" },
  { code: "MH", name: "Wyspy Marshalla" },
  { code: "SB", name: "Wyspy Salomona" },
  { code: "ST", name: "Wyspy Świętego Tomasza i Książęca" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
  { code: "AE", name: "Zjednoczone Emiraty Arabskie" }
];